version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - sWallyx
  assignees:
  - sWallyx
  ignore:
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.24.0
  - dependency-name: discord.js
    versions:
    - 12.5.1
    - 12.5.2
  - dependency-name: ws
    versions:
    - 7.4.2
    - 7.4.3
    - 7.4.4
